USE mydb;

-- Insertion de données dans la table USER
INSERT INTO USER (username, email, password) VALUES ('John Doe', 'john.doe@example.com', 'password123');
INSERT INTO USER (username, email, password) VALUES ('Jane Smith', 'jane.smith@example.com', 'password456');
INSERT INTO USER (username, email, password) VALUES ('John Boyd', 'jaboyd@email.com', 'Culver512');
INSERT INTO USER (username, email, password) VALUES ('Jacob Boyd', 'drk@email.com', 'Culver874');
INSERT INTO USER (username, email, password) VALUES ('Tenley Boyd', 'tenz@email.com', 'password6512');
INSERT INTO USER (username, email, password) VALUES ('Roger Boyd', 'jaboyd@email.com', 'password874');
INSERT INTO USER (username, email, password) VALUES ('Felicia Boyd', 'felicia.boyd@example.com', 'Boyd2915');
INSERT INTO USER (username, email, password) VALUES ('Jonathan Marrack', 'drk@email.com', 'pass97451');
INSERT INTO USER (username, email, password) VALUES ('Tessa Carman', 'tCarman@example.com', 'carbinoc834');
INSERT INTO USER (username, email, password) VALUES ('Peter Duncan', 'duncan.peter@example.com', 'Gershwin644');
INSERT INTO USER (username, email, password) VALUES ('Foster Shepard', 'shepard@example.com', '748townings');
INSERT INTO USER (username, email, password) VALUES ('Tony Cooper', 'coopertony@example.com', 'manchester489');
INSERT INTO USER (username, email, password) VALUES ('Lily Cooper', 'cooperlilly@example.com', 'steppes112');
INSERT INTO USER (username, email, password) VALUES ('Sophia Zemicks', 'soph@email.com', 'password7878');
INSERT INTO USER (username, email, password) VALUES ('Warren Zemicks', 'ward@email.com', 'password841');
INSERT INTO USER (username, email, password) VALUES ('Zach Zemicks', 'zarc@email.com', 'password8547');
INSERT INTO USER (username, email, password) VALUES ('Reginald Walker', 'reg@email.com', 'word908rd');
INSERT INTO USER (username, email, password) VALUES ('Jamie Peters', 'jpeters@email.com', 'jpeters7462');
INSERT INTO USER (username, email, password) VALUES ('Ron Peters', 'ronpeters@email.com', 'ronpet9888');
INSERT INTO USER (username, email, password) VALUES ('Allison Stelzer', 'aly@imail.com', 'password8910');
INSERT INTO USER (username, email, password) VALUES ('Brian Stelzer', 'bstel@email.com', 'password1112');
INSERT INTO USER (username, email, password) VALUES ('Shawna Stelzer', 'ssanw@email.com', 'password1314');
INSERT INTO USER (username, email, password) VALUES ('Kendrik Stelzer', 'kendrikstel@email.com', 'password1516');
INSERT INTO USER (username, email, password) VALUES ('Clive Ferguson', 'ferguson@example.com', 'wordpass123');
INSERT INTO USER (username, email, password) VALUES ('Eric Cadigan', 'eric.cadigan@example.com', 'wordpass951');
INSERT INTO USER (username, email, password) VALUES ('Dean Winchesters', 'deanWinch@imail.com', 'pudding123');
INSERT INTO USER (username, email, password) VALUES ('Samuel Winchesters', 'samy@email.com', 'winchersters3');
INSERT INTO USER (username, email, password) VALUES ('Rohena Ferguson', 'rohena.witch@example.com', 'wizzard2');
INSERT INTO USER (username, email, password) VALUES ('Mark Sheppard', 'mark.sheppard@imail.com', 'kingofH1');
INSERT INTO USER (username, email, password) VALUES ('Tony Stark', 'iamironman@email.com', 'mark22');
INSERT INTO USER (username, email, password) VALUES ('Scarlet Widow', 'black.widow@example.com', 'widow5462');

-- Insertion de données dans la table TRANSACTION
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (1, 2, 'Payment for dinner', 50.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (2, 1, 'Refund for lunch', 30.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (3, 1, 'Payment for birthday gift', 180.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (1, 4, 'Payment for birthday gift', 10.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (6, 2, 'Payment for groceries', 20.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (7, 6, 'Refund for groceries', 130.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (8, 11, 'Refund for loan', 40.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (15, 9, 'Refund for birthday gift', 60.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (10, 14, 'Payment for disney tickets', 70.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (14, 1, 'Payment for shopping', 80.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (5, 1, 'Payment for groceries', 90.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (6, 1, 'Refund for lunch', 5.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (22, 20, 'Payment for dinner', 15.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (16, 20, 'Refund for student loan', 25.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (16, 22, 'Refund for cinema tickets', 35.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (30, 31, 'Refund for birthday gift', 45.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (31, 29, 'Payment for lucnh', 55.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (28, 29, 'Refund for dinner', 65.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (17, 18, 'Payment for dinner', 75.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (18, 19, 'Refund for lunch', 85.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (15, 19, 'Payment for tickets', 95.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (4, 3, 'Payment for gifts', 105.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (5, 3, 'Payment for vacation', 115.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (12, 21, 'Payment for coffee', 22.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (13, 21, 'Payment for coffee shop', 12.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (23, 21, 'Payment for tea', 8.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (1, 5, 'Payment for dinner', 48.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (5, 7, 'Refund for dinner', 27.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (7, 6, 'Payment for lunch', 87.00);
INSERT INTO TRANSACTION (sender_id, receiver_id, description, amount) VALUES (4, 6, 'payment for lunch', 32.00);

-- Insertion de données dans la table CONNECTION
INSERT INTO CONNECTION (userid, connectionId) VALUES (1, 2);
INSERT INTO CONNECTION (userid, connectionId) VALUES (2, 1);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (1, 3);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (3, 1);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (1, 4);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (4, 1);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (6, 2);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (2, 6);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (7, 6);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (6, 7);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (8, 11);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (11, 8);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (15, 9);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (9, 15);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (10, 14);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (14, 10);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (14, 1);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (1, 14);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (5, 1);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (1, 5);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (6, 1);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (1, 6);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (22, 20);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (20, 22);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (16, 20);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (20, 16);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (16, 22);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (22, 16);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (30, 31);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (31, 30);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (31, 29);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (29, 31);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (28, 29);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (29, 28);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (17, 18);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (18, 17);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (18, 19);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (19, 18);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (15, 19);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (19, 15);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (4, 3);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (3, 4);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (5, 3);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (3, 5);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (12, 21);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (21, 12);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (13, 21);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (21, 13);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (23, 21);
INSERT INTO CONNECTION (user_id, connection_id) VALUES (21, 23);